services:
  quote_service:
    build:
      context: ../../../
      dockerfile: apps/microservices-splitdb-with-gateway/Dockerfile.dev
    env_file: ../.env.dev
    volumes:
      - ../src:/app/apps/microservices-splitdb-with-gateway/src
    environment:
      - PORT=${BACKEND_PORT}
      - SERVICE_TYPE=quote
    depends_on:
      - postgres_quote
      - redis
    deploy:
      replicas: 1
    networks:
      - loadbalancing

  quote_nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx-qoute.conf:/etc/nginx/conf.d/default.conf
    networks:
      - loadbalancing
    depends_on:
      - quote_service 
