services:
  user_service:
    build:
      context: ../../../
      dockerfile: apps/microservices-splitdb-with-gateway/Dockerfile.dev
    env_file: ../.env.dev
    volumes:
      - ../src:/app/apps/microservices-splitdb-with-gateway/src
    environment:
      - PORT=${BACKEND_PORT}
      - SERVICE_TYPE=user
    depends_on:
      - postgres_user
      - redis
    deploy:
      replicas: 1
    networks:
      - loadbalancing

  user_nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx-user.conf:/etc/nginx/conf.d/default.conf
    networks:
      - loadbalancing
    depends_on:
      - user_service 
