FROM node:22 AS builder
WORKDIR /app
RUN npm install turbo --global 
COPY . .
RUN turbo prune --scope=microservices-splitdb-with-gateway --docker

FROM node:22 AS installer
WORKDIR /app
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package*.json .
COPY --from=builder /app/turbo.json ./turbo.json
RUN npm install 

FROM node:22 AS sourcer
WORKDIR /app
COPY --from=installer /app/ .
COPY --from=builder /app/out/full/ .
COPY .gitignore .gitignore

FROM node:22 as runner
WORKDIR /app
COPY --from=sourcer /app/ .
WORKDIR /app/apps/microservices-splitdb-with-gateway
CMD ["npm", "run", "start:dev"]
