services:
  db:
    image: postgres:latest
    container_name: db
    restart: on-failure
    env_file: ../.env.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    #   PG_DATA: /var/lib/postgresql/data
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}
    networks:
      - loadbalancing

  redis:
    image: redis:latest
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file: ../.env.dev
    command: redis-server --requirepass ${REDIS_PASS} --port ${REDIS_PORT}
    networks:
      - loadbalancing

networks:
  loadbalancing:
