services:
  other_services:
    build:
      context: ../../../
      dockerfile: apps/microservices/Dockerfile.dev
    env_file: ../.env.dev
    volumes:
      - ../src:/app/apps/microservices/src
    environment:
      - PORT=${BACKEND_PORT}
      - SERVICE_TYPE=other
    depends_on:
      - db
      - redis
    deploy:
      replicas: 2
    networks:
      - loadbalancing

  other_nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx-other.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 82:80
    networks:
      - loadbalancing
    depends_on:
      - other_services 
