services:
  backend:
    container_name: api
    build:
      context: ../../
      dockerfile: apps/monolith/Dockerfile.dev
    env_file: ./.env.dev
    volumes:
      - .:/app/apps/monolith
    environment:
      - PORT=${BACKEND_PORT}
    depends_on:
      - db
      - redis
    command: npm run start:debug
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - 9229:9229

  db:
    image: postgres:latest
    container_name: db
    restart: on-failure
    env_file: ./.env.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    #   PG_DATA: /var/lib/postgresql/data
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}

  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file: ./.env.dev
    command: redis-server --requirepass ${REDIS_PASS} --port ${REDIS_PORT}
